### ISSUE TITLE
[1.19.2-1.0.1] Dynamic lights affect item images in inventory/hotbar

### ISSUE THREAD

**Issue by thimblebird** [BluePaint2/Forge.Dynamic-1.19.2#4]
For comparison:

![2022-10-06_21 15 14](https://user-images.githubusercontent.com/93487547/194399559-e7d85132-8cbd-4737-a7b5-67a53b70c540.png)
![2022-10-06_21 15 25](https://user-images.githubusercontent.com/93487547/194399563-a0f50161-0058-4b8d-9789-06300afcd96b.png)

**Comment by BluePaint2** [comment]
unfortunately that is a side affect of editing shaders, since block shaders are used in inventory and in the world, I can try to fix this for the next update.

**Comment by BluePaint2** [comment]
Fixed this in 1.19.2-1.1.0, 1.18.2-1.1.0, and 1.17.1-1.1.0
