### ISSUE TITLE
[1.19.2-1.0.1] No dynamic lights from placed blocks

### ISSUE THREAD

**Issue by thimblebird** [BluePaint2/Forge.Dynamic-1.19.2#5]
Not really an issue, as it is stated in the fine print of the CurseForge description page that only held/dropped items get dynamic lighting, but for reference and in case others are wondering... as title says:

![2022-10-06_21 21 48](https://user-images.githubusercontent.com/93487547/194400864-acc221b9-ab7f-4e8f-b45f-6d153d1d4dc1.png)

**Comment by BluePaint2** [comment]
Added This information to the mod description, thank you for reminding me!

**Comment by lm4mine** [comment]
Does this mean that the light will never be changed for the posed lights and that it will remain for the carry lights?
