### ISSUE TITLE
particles are not visible in 4 modes

### ISSUE THREAD

**Issue by OlegFive** [BluePaint2/Forge.Dynamic-1.19.2#6]
Forge 1.18.2
OptiFine 1.18.2 HD U H9 pre1

Effective (Forge)
Falling Leaves (Forge)
Visuality: Reforged
Illuminations Forge

**Comment by BluePaint2** [comment]
Thanks for the notice! This happens to be an OptiFine issue, so it may take a while to fix.

**Comment by BluePaint2** [comment]
Issue has been fixed in the recent updates, optifine has issues with which order samplers are in, I moved around the samplers in particle, and they showed up!
